<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 
     * Menú Dinámico 3 Capas:
     * - Personas (usuarios) pertenecen a un Rol
     * - Un Rol contiene un conjunto de Módulos (MenuItems)
     * - Un Módulo puede estar en N Roles
     * - Cada MenuItem tiene ruta, icono, orden y role_id
     */
    public function run(): void
    {
        // Limpiar tabla antes de insertar
        DB::table('menu_items')->truncate();

        $menuItems = [
            // ==============================================
            // MENÚS PARA PROPIETARIO (role_id: 1)
            // ==============================================
            [
                'etiqueta' => 'Dashboard',
                'ruta_laravel' => 'dashboard',
                'icono' => 'bi-house-door-fill',
                'orden' => 10,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Productos (CRUD completo)
            [
                'etiqueta' => 'Productos',
                'ruta_laravel' => 'productos.index',
                'icono' => 'bi-box-seam',
                'orden' => 15,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Crear Producto',
                'ruta_laravel' => 'productos.create',
                'icono' => 'bi-plus-circle',
                'orden' => 16,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Ver Producto',
                'ruta_laravel' => 'productos.show',
                'icono' => 'bi-eye',
                'orden' => 17,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Editar Producto',
                'ruta_laravel' => 'productos.edit',
                'icono' => 'bi-pencil',
                'orden' => 18,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Eliminar Producto',
                'ruta_laravel' => 'productos.destroy',
                'icono' => 'bi-trash',
                'orden' => 19,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Categorías (CRUD completo)
            [
                'etiqueta' => 'Categorías',
                'ruta_laravel' => 'categorias.index',
                'icono' => 'bi-tags',
                'orden' => 20,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Crear Categoría',
                'ruta_laravel' => 'categorias.create',
                'icono' => 'bi-plus-circle',
                'orden' => 21,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Ver Categoría',
                'ruta_laravel' => 'categorias.show',
                'icono' => 'bi-eye',
                'orden' => 22,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Editar Categoría',
                'ruta_laravel' => 'categorias.edit',
                'icono' => 'bi-pencil',
                'orden' => 23,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Eliminar Categoría',
                'ruta_laravel' => 'categorias.destroy',
                'icono' => 'bi-trash',
                'orden' => 24,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Promociones (CRUD completo)
            [
                'etiqueta' => 'Promociones',
                'ruta_laravel' => 'promociones.index',
                'icono' => 'bi-percent',
                'orden' => 25,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Crear Promoción',
                'ruta_laravel' => 'promociones.create',
                'icono' => 'bi-plus-circle',
                'orden' => 26,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Ver Promoción',
                'ruta_laravel' => 'promociones.show',
                'icono' => 'bi-eye',
                'orden' => 27,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Editar Promoción',
                'ruta_laravel' => 'promociones.edit',
                'icono' => 'bi-pencil',
                'orden' => 28,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Eliminar Promoción',
                'ruta_laravel' => 'promociones.destroy',
                'icono' => 'bi-trash',
                'orden' => 29,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Ventas
            [
                'etiqueta' => 'Ventas',
                'ruta_laravel' => 'ventas.index',
                'icono' => 'bi-receipt',
                'orden' => 30,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Pedidos (CRUD completo - gestión de pedidos pendientes)
            [
                'etiqueta' => 'Pedidos',
                'ruta_laravel' => 'pedidos.index',
                'icono' => 'bi-clipboard-check',
                'orden' => 31,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Ver Pedido',
                'ruta_laravel' => 'pedidos.show',
                'icono' => 'bi-eye',
                'orden' => 32,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Confirmar Pedido',
                'ruta_laravel' => 'pedidos.confirmar',
                'icono' => 'bi-check-circle',
                'orden' => 33,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Cancelar Pedido',
                'ruta_laravel' => 'pedidos.cancelar',
                'icono' => 'bi-x-circle',
                'orden' => 34,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Usuarios (CRUD completo)
            [
                'etiqueta' => 'Usuarios',
                'ruta_laravel' => 'usuarios.index',
                'icono' => 'bi-people',
                'orden' => 35,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Crear Usuario',
                'ruta_laravel' => 'usuarios.create',
                'icono' => 'bi-person-plus',
                'orden' => 36,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Ver Usuario',
                'ruta_laravel' => 'usuarios.show',
                'icono' => 'bi-eye',
                'orden' => 37,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Editar Usuario',
                'ruta_laravel' => 'usuarios.edit',
                'icono' => 'bi-pencil',
                'orden' => 38,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Eliminar Usuario',
                'ruta_laravel' => 'usuarios.destroy',
                'icono' => 'bi-trash',
                'orden' => 39,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Créditos',
                'ruta_laravel' => 'creditos.index',
                'icono' => 'bi-credit-card-fill',
                'orden' => 40,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Crear Crédito',
                'ruta_laravel' => 'creditos.create',
                'icono' => 'bi-plus-circle',
                'orden' => 41,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Editar Crédito',
                'ruta_laravel' => 'creditos.edit',
                'icono' => 'bi-pencil',
                'orden' => 42,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Eliminar Crédito',
                'ruta_laravel' => 'creditos.destroy',
                'icono' => 'bi-trash',
                'orden' => 43,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Pagos',
                'ruta_laravel' => 'pagos.index',
                'icono' => 'bi-cash-coin',
                'orden' => 50,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Registrar Pago',
                'ruta_laravel' => 'pagos.create',
                'icono' => 'bi-plus-circle',
                'orden' => 51,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Editar Pago',
                'ruta_laravel' => 'pagos.edit',
                'icono' => 'bi-pencil',
                'orden' => 52,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Eliminar Pago',
                'ruta_laravel' => 'pagos.destroy',
                'icono' => 'bi-trash',
                'orden' => 53,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Reportes',
                'ruta_laravel' => 'reportes.index',
                'icono' => 'bi-graph-up',
                'orden' => 60,
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==============================================
            // MENÚS PARA VENDEDOR (role_id: 2)
            // ==============================================
            [
                'etiqueta' => 'Dashboard',
                'ruta_laravel' => 'dashboard',
                'icono' => 'bi-house-door-fill',
                'orden' => 10,
                'role_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Productos',
                'ruta_laravel' => 'productos.index',
                'icono' => 'bi-box-seam',
                'orden' => 15,
                'role_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Ver Producto',
                'ruta_laravel' => 'productos.show',
                'icono' => 'bi-eye',
                'orden' => 16,
                'role_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Ventas',
                'ruta_laravel' => 'ventas.index',
                'icono' => 'bi-receipt',
                'orden' => 20,
                'role_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Pedidos (gestión de pedidos pendientes)
            [
                'etiqueta' => 'Pedidos',
                'ruta_laravel' => 'pedidos.index',
                'icono' => 'bi-clipboard-check',
                'orden' => 21,
                'role_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Ver Pedido',
                'ruta_laravel' => 'pedidos.show',
                'icono' => 'bi-eye',
                'orden' => 22,
                'role_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Confirmar Pedido',
                'ruta_laravel' => 'pedidos.confirmar',
                'icono' => 'bi-check-circle',
                'orden' => 23,
                'role_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Cancelar Pedido',
                'ruta_laravel' => 'pedidos.cancelar',
                'icono' => 'bi-x-circle',
                'orden' => 24,
                'role_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Créditos',
                'ruta_laravel' => 'creditos.index',
                'icono' => 'bi-credit-card-fill',
                'orden' => 30,
                'role_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Crear Crédito',
                'ruta_laravel' => 'creditos.create',
                'icono' => 'bi-plus-circle',
                'orden' => 31,
                'role_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Pagos',
                'ruta_laravel' => 'pagos.index',
                'icono' => 'bi-cash-coin',
                'orden' => 40,
                'role_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Registrar Pago',
                'ruta_laravel' => 'pagos.create',
                'icono' => 'bi-plus-circle',
                'orden' => 41,
                'role_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Reportes',
                'ruta_laravel' => 'reportes.index',
                'icono' => 'bi-graph-up',
                'orden' => 50,
                'role_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==============================================
            // MENÚS PARA CLIENTE (role_id: 3)
            // ==============================================
            [
                'etiqueta' => 'Dashboard',
                'ruta_laravel' => 'dashboard',
                'icono' => 'bi-house-door-fill',
                'orden' => 10,
                'role_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Productos',
                'ruta_laravel' => 'productos.index',
                'icono' => 'bi-box-seam',
                'orden' => 15,
                'role_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Ver Producto',
                'ruta_laravel' => 'productos.show',
                'icono' => 'bi-eye',
                'orden' => 16,
                'role_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Promociones',
                'ruta_laravel' => 'promociones.index',
                'icono' => 'bi-percent',
                'orden' => 20,
                'role_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Ver Promoción',
                'ruta_laravel' => 'promociones.show',
                'icono' => 'bi-eye',
                'orden' => 21,
                'role_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Mi Carrito',
                'ruta_laravel' => 'carritos.index',
                'icono' => 'bi-cart-fill',
                'orden' => 25,
                'role_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Mis Pedidos',
                'ruta_laravel' => 'mis-pedidos.index',
                'icono' => 'bi-bag-check-fill',
                'orden' => 30,
                'role_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Mis Créditos',
                'ruta_laravel' => 'mis-creditos.index',
                'icono' => 'bi-wallet2',
                'orden' => 35,
                'role_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'etiqueta' => 'Mis Pagos',
                'ruta_laravel' => 'mis-pagos.index',
                'icono' => 'bi-cash-coin',
                'orden' => 40,
                'role_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('menu_items')->insert($menuItems);

        $this->command->info('✅ Menú dinámico por roles insertado correctamente.');
        $this->command->info('   - Propietario: CRUD completo (Productos, Categorías, Promociones, Ventas, Pedidos, Usuarios, Créditos, Pagos, Reportes)');
        $this->command->info('   - Vendedor: Productos (ver), Ventas, Pedidos (confirmar/cancelar), Créditos (crear), Pagos (registrar), Reportes');
        $this->command->info('   - Cliente: Dashboard, Productos (ver), Promociones (ver), Mi Carrito, Mis Pedidos, Mis Créditos, Mis Pagos');
    }
}
